### ISSUE TITLE
Using seathru.py/seathru-mono-e2e.py file on an image in a local dataset

### ISSUE THREAD

**Issue by techrishikb** [jgibson2/sea-thru#9]
Hi jgibson2,

Thanks for the beautifull work. Your guidance would help me to move forward.

But when I am trying to use the file(seathru.py/seathru-mono-e2e.py) on an underwater image presnt in the local system, some issues are been faced.
python seathru.py --image Raw/E:/SeaThru/sea-thru/images/fog.jpg --depth-map depthMaps/...

Can you please let me know what should be the depth map path or how to create the depth map when we are using image from a local path?

Can you please provide a sample sysntax to be used in cmd along with --image and --depth-map?

python seathru-mono-e2e.py --monodepth-add-depth 1.0 --monodepth-multiply-depth 3.0 --image Raw/E:/SeaThru/sea-thru/images/fog.jpg --raw --output output-monodepth.png

"Traceback (most recent call last):
  File "seathru-mono-e2e.py", line 125, in <module>
    run(args)
  File "seathru-mono-e2e.py", line 68, in run
    img = Image.fromarray(rawpy.imread(args.image).postprocess()) if args.raw else pil.open(args.image).convert('RGB')
  File "C:\Users\Rishi\Anaconda3\envs\yolo\lib\site-packages\rawpy\__init__.py", line 20, in imread
    d.open_file(pathOrFile)
  File "rawpy\_rawpy.pyx", line 409, in rawpy._rawpy.RawPy.open_file
  File "rawpy\_rawpy.pyx", line 936, in rawpy._rawpy.RawPy.handle_error
rawpy._rawpy.LibRawIOError: b'Input/output error'"

Can you please help me in this?

Kindly let me know in case of any questions.

Thanks in advance

**Comment by jgibson2** [comment]
You have the `--raw` argument which would indicate that you want to run it with a .ARW / .RAW camera image (i.e. the output you get directly out of the camera). Try omitting that argument.

**Comment by techrishikb** [comment]
Hi,
Thanks for the reply. It worked and the error for seathru-mono-e2e.py were eliminated successfully.

But when I am trying to run the seathru.py file alone it is asking for depth-map value. Can you please help me in understanding how to get the depth-map value for a image.?
syntax run and error in cmd:

(yolo) E:\SeaThru\sea-thru>python seathru.py --image E:/SeaThru/sea-thru/images/fog.jpg
usage: seathru.py [-h] --image IMAGE --depth-map DEPTH_MAP [--output OUTPUT] [--f F] [--l L] [--p P]
                  [--min-depth MIN_DEPTH] [--max-depth MAX_DEPTH] [--spread-data-fraction SPREAD_DATA_FRACTION]
                  [--size SIZE] [--output-graphs] [--preprocess-for-monodepth] [--monodepth]
                  [--monodepth-add-depth MONODEPTH_ADD_DEPTH] [--monodepth-multiply-depth MONODEPTH_MULTIPLY_DEPTH]
                  [--equalize-image]
seathru.py: error: the following arguments are required: --depth-map

Can you please help me in setting the depth map value?

Thanks in advence

**Comment by jgibson2** [comment]
You need a depth map to run the original method. Part of what I did was to augment this with monodepth2, which provides a depth map from a single image (though it is not perfect). If you run the `seathru-mono-e2e.py` command it should automatically calculate the depth map using monodepth2.

**Comment by techrishikb** [comment]
Hi jgibson2,

Thanks for the update. Your replies are really helping a lot..

Currently i am trying to process a single image after running the python files.

Can multiple image files in a folder can be run at a same time to generate multiple output in a specific folder.?

Thanks in advance..

**Comment by jgibson2** [comment]
Not at the moment, but you could pretty easily rig up a bash script
